project:
  type: website
  output-dir: docs

website:
  title: "Armá tu CV con positron"
  
  page-footer:
    left: "&copy; 2026 Ariana Bardauil"
    right: "Website construida con [Quarto](https://quarto.org/)."
    background: "#2A5F8E"
  
  sidebar:
    background: "#2A5F8E"
    logo: logo.png
    pinned: true
    align: center
    style: docked
    type: dark
    
    contents:
      - href: index.qmd
        text: ¿Qué necesitamos?
      - href: about.qmd
        text: Diapositivas
      - href: taller.qmd
        text: Taller

format:
  html:
    theme: [flatly, styles.scss]
    toc: false

editor: visual


